# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

version: 0.2

phases:
  build:
    commands:
      - packer build -color=false
          -var version_id=${CODEBUILD_SOURCE_VERSION}
          -var resolved_version_id=${CODEBUILD_RESOLVED_SOURCE_VERSION}
          -var build_id=${CODEBUILD_BUILD_ID}
          -var subnet_id=${SUBNET_ID}
          -var kms_key_id=${KMS_KEY_ID}
          packer.json

artifacts:
  files:
    - manifest.json
    - test/**/*
